repos:
- repo: local
  hooks:
    - id: format
      name: format
      entry: make format
      language: system
      pass_filenames: false
      always_run: true
      verbose: true

    - id: lint
      name: lint
      entry: make lint
      language: system
      pass_filenames: false
      always_run: true
      verbose: true

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-merge-conflict
